# -*- coding: utf-8 -*-
"""DATAVIZ_BANKAI_PANEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9wg-8qjGTCrEYSzlWgdJmeQl2mAorIJ

# **Preparing the data**
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import matplotlib.colors
import panel as pn
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
import plotly.graph_objs as go

df = pd.read_csv('/Users/mikhaellaserezo/Downloads/Unicorn_Companies.tsv', sep='\t')

df['Founded Year'] = pd.to_numeric(df['Founded Year'], errors='coerce')
df['Valuation ($B)'] = df['Valuation ($B)'].replace('[\$,]', '', regex=True).astype(float)
df.dropna(subset=['Founded Year'], inplace=True)
df['Founded Year'] = df['Founded Year'].astype(int)

df['Valuation ($M)'] = df['Valuation ($B)'] * 1000

df.head()

valid_industries = [
    'Artificial intelligence', 'Other', 'Fintech',
    'Internet software & services', 'Supply chain, logistics, & delivery',
    'Data management & analytics', 'E-commerce & direct-to-consumer', 'Edtech',
    'Hardware', 'Consumer & retail', 'Health', 'Auto & transportation',
    'Cybersecurity', 'Mobile & telecommunications', 'Travel'
]

# Correction 'Finttech' to 'Fintech'
df['Industry'] = df['Industry'].replace('Finttech', 'Fintech')

# Remplacement the non valid values by 'Other'
df['Industry'] = df['Industry'].apply(lambda x: x if x in valid_industries else 'Other')

print(df['Industry'].unique())

# Adjsting orders of magnitude
def convert_raised_amount(raised_str):
    if pd.isnull(raised_str):
        return 0
    raised_str = raised_str.upper().replace('$', '').strip()
    multiplier = 1
    if 'B' in raised_str:
        multiplier = 1000000000
        raised_str = raised_str.replace('B', '')
    elif 'M' in raised_str:
        multiplier = 1000000
        raised_str = raised_str.replace('M', '')
    elif 'K' in raised_str:
        multiplier = 1000
        raised_str = raised_str.replace('K', '')

    try:
        return float(raised_str) * multiplier
    except ValueError:  # Au cas où la conversion échoue
        return 0


df['Total Raised ($M)'] = df['Total Raised'].apply(convert_raised_amount) / 1000000  # Convertir en millions de dollars

"""# **Creating Panel Application**"""

pn.extension('plotly')

# Function Definitions
def map_value_to_color(value, min_val, max_val, color_scale):
    value_scaled = (value - min_val) / (max_val - min_val)
    for i, (limit, color) in enumerate(color_scale):
        if value_scaled <= limit:
            lower_limit, lower_color = color_scale[i-1] if i > 0 else (0, color)
            upper_limit, upper_color = color_scale[i]
            ratio = (value_scaled - lower_limit) / (upper_limit - lower_limit)
            return interpolate_color(lower_color, upper_color, ratio)
    return color_scale[-1][1]

def interpolate_color(color1, color2, ratio):
    color1_rgb = matplotlib.colors.hex2color(color1)
    color2_rgb = matplotlib.colors.hex2color(color2)
    inter_color = [((1 - ratio) * c1 + ratio * c2) for c1, c2 in zip(color1_rgb, color2_rgb)]
    return matplotlib.colors.rgb2hex(inter_color)


# Page 1 Components
@pn.depends()
def page_1_view():
    unicorn_counts = df['Founded Year'].value_counts().reset_index()
    unicorn_counts.columns = ['Founded Year', 'Number of Unicorns']
    unicorn_counts.sort_values('Founded Year', inplace=True)
    fig_unicorn_counts = px.bar(unicorn_counts, x='Founded Year', y='Number of Unicorns', labels={'Number of Unicorns': 'Number of Unicorns', 'Founded Year': 'Founded Year'}, title="Number of Unicorns Founded per Year")

    valuation_by_year = df.groupby('Founded Year')['Valuation ($B)'].sum().reset_index()
    fig_valuation_by_year = px.line(valuation_by_year, x='Founded Year', y='Valuation ($B)', labels={'Valuation ($B)': 'Total Valuation ($B)', 'Founded Year': 'Founded Year'}, title="Evolution of Total Unicorn Valuation over the Years")

    top_10_valued_companies = df.nlargest(10, 'Valuation ($B)')  # Sélectionner les 10 entreprises avec la plus grande valuation
    fig_top_10_valued = px.bar(top_10_valued_companies, x='Valuation ($B)', y='Company', orientation='h', labels={'Valuation ($B)': 'Valuation ($B)', 'Company': 'Company'}, title='Top 10 Most Valuable Companies',  color='Country')

    title = pn.pane.Markdown("# Global Overview of the Unicorns Landscape")
    second_row = pn.Row(fig_unicorn_counts, fig_valuation_by_year)
    third_row = pn.Row(fig_top_10_valued)
    layout = pn.Column(title, second_row, third_row)

    return layout

# Global variable to hold the selected country
selected_country = pn.widgets.StaticText(name='Selected Country', value='')

# Update functions for the interactive charts
def update_bar_chart(country):
    if not country:
        return go.Figure()

    companies = df[df['Country'] == country].nlargest(10, 'Valuation ($B)')
    return px.bar(
        companies,
        x='Valuation ($B)',
        y='Company',
        title=f'Top 10 Companies in {country}',
        orientation='h',
        color='Valuation ($B)',
        color_continuous_scale='Blues'
    )

def update_pie_chart(country):
    if not country:
        return go.Figure()

    industries = df[df['Country'] == country]['Industry'].value_counts().reset_index()
    industries.columns = ['Industry', 'Count']
    return px.pie(
        industries,
        values='Count',
        names='Industry',
        title=f'Industries Distribution in {country}'
    )

def update_time_series(country):
    if not country:
        return go.Figure()

    funding_data = df[df['Country'] == country].groupby('Founded Year')['Total Raised ($M)'].sum().reset_index()
    return px.line(
        funding_data,
        x='Founded Year',
        y='Total Raised ($M)',
        title=f'Total Funding Over Time in {country}',
        markers=True
    )

# View function for the interactive charts
@pn.depends(selected_country.param.value)
def interactive_charts_view(country):
    if not country:
        return pn.pane.Markdown("Please click on a country to see the data")

    bar_chart = update_bar_chart(country)
    pie_chart = update_pie_chart(country)
    time_series = update_time_series(country)

    return pn.Row(pn.pane.Plotly(bar_chart),
                     pn.pane.Plotly(pie_chart),
                     pn.pane.Plotly(time_series))

@pn.depends()
def page_2_view():
    # Data
    unicorns_per_country = df['Country'].value_counts().reset_index(name='Number of Unicorns')
    unicorns_per_country.columns = ['Country', 'Number of Unicorns']

    # Personnalized color scale
    color_scale_custom = [(0, "#add8e6"), (0.5, "#0000ff"), (1, "#00008b")]


    top_countries = unicorns_per_country.head(10)
    min_val = unicorns_per_country['Number of Unicorns'].min()
    max_val = unicorns_per_country['Number of Unicorns'].max()
    bar_colors = [map_value_to_color(val, min_val, max_val, color_scale_custom) for val in top_countries['Number of Unicorns']]


    fig = make_subplots(rows=1, cols=2, specs=[[{"type": "choropleth"}, {"type": "bar"}]], column_widths=[0.7, 0.3])

    # Choropleth
    choropleth_trace = go.Choropleth(
        locations=unicorns_per_country['Country'],
        locationmode='country names',
        z=unicorns_per_country['Number of Unicorns'],
        colorscale= color_scale_custom,
        colorbar_title="Number of Unicorns",
        hoverinfo='location+z'
    )
    fig.add_trace(choropleth_trace, row=1, col=1)

    # Bar plot
    for i, country in enumerate(top_countries['Country']):
        fig.add_trace(
            go.Bar(
                x=[top_countries['Number of Unicorns'].iloc[i]],
                y=[country],
                orientation='h',
                marker=dict(color=bar_colors[i]),
                hoverinfo='x+y'
            ),
            row=1, col=2
        )

    # Layout
    fig.update_layout(
        title_text='Global Distribution of Unicorn Companies and Top 10 Countries',
        width=1500,
        height=800,
        showlegend=False
    )
    fig.update_yaxes(title_text="Country", row=1, col=2)
    fig.update_xaxes(title_text="Number of Unicorns", row=1, col=2)


    choropleth_pane = pn.pane.Plotly(fig)
    choropleth_pane.param.watch(lambda event: setattr(selected_country, 'value', event.new['points'][0]['location']) if event.new else None, 'click_data')

    return pn.Column(pn.pane.Markdown("# The goegraphy of Innovation"),choropleth_pane, interactive_charts_view)

@pn.depends()
def page_3_view():

    # Slider for Year Range
    min_year = int(df['Founded Year'].min())
    max_year = int(df['Founded Year'].max())
    year_slider = pn.widgets.IntRangeSlider(name='Select Year Range', start=min_year, end=max_year, value=(min_year, max_year), step=1)

    # Treemap Interactive Visualization
    @pn.depends(year_slider.param.value)
    def filtered_treemap(year_range):
        filtered_df = df[(df['Founded Year'] >= year_range[0]) & (df['Founded Year'] <= year_range[1])]
        valuation_by_industry = filtered_df.groupby('Industry')['Valuation ($B)'].sum().reset_index()
        colors = ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0', '#9966FF', '#FF9F40']
        fig_treemap = px.treemap(
            valuation_by_industry,
            path=['Industry'],
            values='Valuation ($B)',
            title=f'Total value per industry from {year_range[0]} to {year_range[1]}',
            color_discrete_sequence=colors
        )


        fig_treemap.update_layout(width=1500, height=600)


        return pn.pane.Plotly(fig_treemap, sizing_mode='stretch_width')

    return pn.Column(pn.pane.Markdown("# Embracing the Digital Revolution: Pioneering Towards an Evermore Digitized Industry"),year_slider, filtered_treemap)

# Dropdown
industry_selector = pn.widgets.Select(name='Select Industry', options=df['Industry'].unique().tolist(), value=df['Industry'].unique()[0])

# Update the pie chart
def update_pie_2_chart(industry):
    filtered_df = df[df['Industry'] == industry]
    deal_terms = filtered_df['Deal Terms'].sum()
    portfolio_exits = filtered_df['Portfolio Exits'].sum()

    pie_fig = go.Figure(data=[go.Pie(labels=['Deal Terms', 'Portfolio Exits'],
                                     values=[deal_terms, portfolio_exits], hole=.4)])
    pie_fig.update_traces(hoverinfo="label+percent+name+value")
    pie_fig.update_layout(title_text=f"Deal Terms vs. Portfolio Exits for {industry}", width = 1000, height = 400)
    return pie_fig

# Update the stacked area chart
def update_area_chart(industry):
    filtered_df = df[df['Industry'] == industry]

    area_fig = go.Figure()
    area_fig.add_trace(go.Scatter(x=filtered_df['Founded Year'], y=filtered_df['Valuation ($M)'],
                                  stackgroup='one', name='Valuation ($M)'))
    area_fig.add_trace(go.Scatter(x=filtered_df['Founded Year'], y=filtered_df['Total Raised ($M)'],
                                  stackgroup='one', name='Total Raised ($M)'))
    area_fig.update_layout(title_text=f"Valuation and Total Raised over Time for {industry}", width = 1000, height = 400)
    return area_fig


@pn.depends(industry_selector.param.value)
def reactive_pie_chart(industry):
    return pn.pane.Plotly(update_pie_2_chart(industry), height=350)

@pn.depends(industry_selector.param.value)
def reactive_area_chart(industry):
    return pn.pane.Plotly(update_area_chart(industry), height=350)


def page_4_view():
    return pn.Column(
        pn.pane.Markdown("# How attractive is each sector?"),
        industry_selector,
        pn.Row(reactive_pie_chart, reactive_area_chart)
    )

tabs = pn.Tabs(
    ("Introduction", page_1_view),
    ("Geography Analysis", page_2_view),
    ("Industry Analysis - Overview", page_3_view),
    ("Industry Analysis - Financial Analysis", page_4_view),

)

tabs.servable()
